### ISSUE TITLE
not match RegExp  - Flutter 3.0.1 on Web only

### ISSUE THREAD

**Issue by pauline-jubiliz** [brianegan/transparent_image#12]
Hello,

Since the Flutter 3 update, when using "kTransparentImage", an error occurs. 

I made all the necessary checks, it is indeed "kTransparentImage" which poses problem.
There is no such problem on android and IOS

`FadeInImage(
                        placeholder: MemoryImage(kTransparentImage),
                        image: _myImage,
                      )`

On the screen, you can see "Invalid Argument: Unexpected end of the image. Request for frame index 0 can't be satisfied."

In the console : 
« Error: Assertion failed:
../…/foundation/stack_frame.dart:112
match != null
"Expected Non-error `null` thrown by JS does not have stack trace. to match RegExp/^(.+) (\\d+):(\\d+)\\s+(.+)$/."
    at Object.throw_ [as throw] (http://localhost:8000/dart_sdk.js:5080:11)
    at Object.assertFailed (http://localhost:8000/dart_sdk.js:5005:15)
at Function._parseWebDebugFrame (http://localhost:8000/packages/flutter/src/foundation/stack_frame.dart.lib.js:178:34)
at Function._parseWebFrame (http://localhost:8000/packages/flutter/src/foundation/stack_frame.dart.lib.js:169:39)
at MappedIterator.new.fromStackTraceLine (http://localhost:8000/packages/flutter/src/foundation/stack_frame.dart.lib.js:210:39)
    at MappedIterator.new.moveNext (http://localhost:8000/dart_sdk.js:24325:71)
 at MappedIterator.new.moveNext (http://localhost:8000/dart_sdk.js:24325:71)
    at WhereTypeIterator.new.moveNext (http://localhost:8000/dart_sdk.js:25397:31)
    at JsIterator.next (http://localhost:8000/dart_sdk.js:6900:21)
    at Function.of (http://localhost:8000/dart_sdk.js:46838:18)
    at WhereTypeIterable.new.toList (http://localhost:8000/dart_sdk.js:22408:30)
at Function.fromStackString (http://localhost:8000/packages/flutter/src/foundation/stack_frame.dart.lib.js:165:187)
at defaultStackFilter (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:3686:49)
at Function._applyStackFilter (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:3842:20)
at new assertions.DiagnosticsStackTrace.new (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:3855:135)
at assertions.FlutterErrorDetails.new.debugFillProperties (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:3553:24)
at http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:2597:26
t assertions._FlutterErrorDetailsNode.new.get builder (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:2600:30)
at assertions._FlutterErrorDetailsNode.new.get builder [as builder] (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:3880:27)
at assertions._FlutterErrorDetailsNode.new.getProperties (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:2612:71)
at diagnostics$.TextTreeRenderer.new.[_debugRender] (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:1256:37)
at diagnostics$.TextTreeRenderer.new.render (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:1170:34)
at dumpErrorToConsole (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:3670:128)
at Function.reportError (http://localhost:8000/packages/flutter/src/foundation/debug.dart.lib.js:3765:27)
at image_stream.MultiFrameImageStreamCompleter.new.reportError (http://localhost:8000/packages/flutter/src/painting/image_stream.dart.lib.js:507:33)
at image_stream.MultiFrameImageStreamCompleter.new.reportError (http://localhost:8000/packages/flutter/src/painting/image_stream.dart.lib.js:507:33)
at image_stream.MultiFrameImageStreamCompleter.new._decodeNextFrameAndSchedule (http://localhost:8000/packages/flutter/src/painting/image_stream.dart.lib.js:668:18)
    at _decodeNextFrameAndSchedule.throw (<anonymous>)
    at http://localhost:8000/dart_sdk.js:40646:38
    at _RootZone.runBinary (http://localhost:8000/dart_sdk.js:40515:59)
    at _FutureListener.thenAwait.handleError (http://localhost:8000/dart_sdk.js:35449:33)
    at handleError (http://localhost:8000/dart_sdk.js:36015:51)
    at Function._propagateToListeners (http://localhost:8000/dart_sdk.js:36041:17)
    at _Future.new.[_completeError] (http://localhost:8000/dart_sdk.js:35878:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:8000/dart_sdk.js:35927:31)
    at Object._microtaskLoop (http://localhost:8000/dart_sdk.js:40778:13)
    at _startMicrotaskLoop (http://localhost:8000/dart_sdk.js:40784:13)
    at http://localhost:8000/dart_sdk.js:36261:9"

Flutteur doctor : 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3.1 21E258 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by ricardoboss** [comment]
I got the same issue.

**Comment by dmytro-kashcheiev** [comment]
Got the same issue with `3.1.0` from the beta channel.

**Comment by bmennear** [comment]
Experiencing the same issue, also with 3.0.1 stable.

**Comment by sgehrman** [comment]
Similar issue.  I'm on 3.0.2 stable

It was working, but decided to try canvasKit renderer on my web app and FadeInImage seems to fail.

I'm also using kTransparentImage.

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.2, on Debian GNU/Linux 11 (bullseye) 5.10.0-15-amd64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

**Comment by sgehrman** [comment]
The kTransparentImage from the flutter source is different now.

const List<int> kTransparentImage = <int>[
  0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49,
  0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06,
  0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, 0x06, 0x62, 0x4B,
  0x47, 0x44, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0xA0, 0xBD, 0xA7, 0x93, 0x00,
  0x00, 0x00, 0x09, 0x70, 0x48, 0x59, 0x73, 0x00, 0x00, 0x0B, 0x13, 0x00, 0x00,
  0x0B, 0x13, 0x01, 0x00, 0x9A, 0x9C, 0x18, 0x00, 0x00, 0x00, 0x07, 0x74, 0x49,
  0x4D, 0x45, 0x07, 0xE6, 0x03, 0x10, 0x17, 0x07, 0x1D, 0x2E, 0x5E, 0x30, 0x9B,
  0x00, 0x00, 0x00, 0x0B, 0x49, 0x44, 0x41, 0x54, 0x08, 0xD7, 0x63, 0x60, 0x00,
  0x02, 0x00, 0x00, 0x05, 0x00, 0x01, 0xE2, 0x26, 0x05, 0x9B, 0x00, 0x00, 0x00,
  0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
];

**Comment by sgehrman** [comment]
that seems to work.

**Comment by razfazz** [comment]
@sgehrman  thank you!

to use this with FadeInImage

```
const List<int> kTransparentImage = [
  0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49,
  0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06,
  0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, 0x06, 0x62, 0x4B,
  0x47, 0x44, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0xA0, 0xBD, 0xA7, 0x93, 0x00,
  0x00, 0x00, 0x09, 0x70, 0x48, 0x59, 0x73, 0x00, 0x00, 0x0B, 0x13, 0x00, 0x00,
  0x0B, 0x13, 0x01, 0x00, 0x9A, 0x9C, 0x18, 0x00, 0x00, 0x00, 0x07, 0x74, 0x49,
  0x4D, 0x45, 0x07, 0xE6, 0x03, 0x10, 0x17, 0x07, 0x1D, 0x2E, 0x5E, 0x30, 0x9B,
  0x00, 0x00, 0x00, 0x0B, 0x49, 0x44, 0x41, 0x54, 0x08, 0xD7, 0x63, 0x60, 0x00,
  0x02, 0x00, 0x00, 0x05, 0x00, 0x01, 0xE2, 0x26, 0x05, 0x9B, 0x00, 0x00, 0x00,
  0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
];
```

```
   FadeInImage.memoryNetwork(
                          placeholder: Uint8List.fromList(kTransparentImage),
                          image: 'yourURL',
                        ),
```

**Comment by edunnett** [comment]
I had this issue as well. I was using a FadeInImage on web. Like others, I just changed the image bytes. Below works for me as a drop-in replacement.
```

import 'package:flutter/foundation.dart';
final Uint8List kTransparentImage = Uint8List.fromList(<int>[
  0x47,
  0x49,
  0x46,
  0x38,
  0x39,
  0x61,
  0x1,
  0x00,
  0x1,
  0x00,
  0x80,
  0x00,
  0x00,
  0xff,
  0xff,
  0xff,
  0xff,
  0xff,
  0xff,
  0x21,
  0xf9,
  0x04,
  0x1,
  0x0a,
  0x00,
  0x1,
  0x00,
  0x2c,
  0x00,
  0x00,
  0x00,
  0x00,
  0x1,
  0x00,
  0x1,
  0x0,
  0x00,
  0x2,
  0x2,
  0x4c,
  0x1,
  0x00,
  0x3b
]);
```

**Comment by brianegan** [comment]
Fixed in latest version
